### ISSUE TITLE
Question regarding Hashimoto Filter

### ISSUE THREAD

**Issue by eereenah-fast** [molecule-generator-collection/ChemTSv2#24]
Hello, thanks a lot for sharing your work!

I was wondering whether you could provide any relevant literature regarding the `hashimoto_filter` available in general filters? I could not find any information regarding the filter in the paper/over the internet.

Thanks a lot in advance!

**Comment by sishida21** [comment]
@eereenah-fast, Thank you very much for using ChemTSv2. 

I'm sorry for the confusion caused by the filter name. The filter was reported by Ma et al[^1]. and is based on the frequency of occurrence of molecular patterns in the PubChem database. In the latest version, I renamed `hashimoto_filter` to `pubchem_filter` and added a document about filter functions in [filter/README.md](https://github.com/molecule-generator-collection/ChemTSv2/tree/master/filter). So, please upgrade the chemtsv2 python version and pull the latest version of the GitHub repository to update config files. 

Best regards.

[^1]: Ma, B., Terayama, K., Matsumoto, S., Isaka, Y., Sasakura, Y., Iwata, H., Araki, M., & Okuno, Y. (2021). Structure-Based de Novo Molecular Generator Combined with Artificial Intelligence and Docking Simulations. Journal of Chemical Information and Modeling, 61(7), 3304–3313. https://doi.org/10.1021/acs.jcim.1c00679
